### PR TITLE
Fix mobile UI

### LINKED ISSUE #1: Mobile UI
I downloaded this extension on android through the Kiwi Browser and I really like the extension but it's kinda broken on mobile as seen on the screenshots below. The download button is on top of the navigation bar and the download modal is off-center. The text could also be changed to an icon.
Screenshot_20230127-211038_Kiwi Browser
Screenshot_20230127-211158_Kiwi Browser

### PR DESCRIPTION
**Pull request by Kyiro**
This pull request will close #1.

### CODE REVIEW

**Comment by Kyiro** [comment]
I acidentally broke something on chrome by the second commit. Hold on.

**Comment by HOAIAN2** [comment]
Ok, still on Lunar New Year vacations but I just check your code, here is something I found.
1. handleDownload() logic: It's should open display container everytime when user click. When I press download and switch to other post, it's not download it close and I must press again.
2. Mobile styles is good but display container should have fixed positions because when I scroll down, it's lose.

**Comment by Kyiro** [comment]
I will fix the first thing you mentioned but the second one only happens on small screens and won't affect desktop.

**Comment by HOAIAN2** [comment]
Do you have Instagram? Contact me: hoaian.2202 I will show you styles on mobile. I can't upload video on Github

**Comment by HOAIAN2** [comment]
I just forgot Google Photos. Check this, scroll down and press Download.
https://photos.app.goo.gl/GgihsdTRm4KCx7ULA

**Comment by Kyiro** [comment]
My bad, I accidentally set the position to be absolute instead of fixed like it is normally

**Comment by Kyiro** [comment]
It should all be fine now

**Pull request merged**
